### ISSUE TITLE
linux script issue with xdelta3

### ISSUE THREAD

**Issue by otaolafranc** [Trixarian/NetherSX2-patch#56]
Hello, 
I am having issues with the linux script:
```
chmod +x build-nethersx2.sh
./build-nethersx2.sh
========================
 NetherSX2 Builder v1.8
========================
Downloading AetherSX2...[Done]
Patching to NetherSX2...xdelta3: source file too short: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent
[Done]
Press Enter to exit...
```
regards

**Comment by suckawha** [comment]
The issue I ran into is that `curl` is ignorant to the redirect to download the release binary, if you update the `curl` incantation to account for the redirect with the `-L` flag it'll download the package. Alternatively you could swap it out for `wget` and change the line to work.

```
-L, --location        Follow redirects
```

Which was roughly line 65 in the shell script.

```
curl -L -s -o "$input_path/15210-v1.5-4248.apk" "https://github.com/Trixarian/NetherSX2-patch/releases/download/0.0/15210-v1.5-4248.apk"
```

The other issue I ran into was that the `xdelta3` binary was being made executable with an incantation that `chmod` did not approve of, so I have to change line 53 to look like:

```
chmod a+x $p2f/lib/xdelta3
```

Then everything worked.

**Comment by Trixarian** [comment]
This was a bug and suckawha's solution is how you fix it. This has been fixed and will ship with 1.9 onward

**Comment by GhostOps77** [comment]
Now im having this issue
and even though i ran that chmod command manually, i still get the 'Permission denied' error msg

**Comment by nighto** [comment]
Needed to replace `xdelta3` with `./lib/xdelta3`  to make it work
